=== yun79831/toolTest/src/config/codemapping/codemapping.xsd
<?xml version="1.0" encoding="utf-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="constants">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="constant" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="constant">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="item"  minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" />
			<xsd:attribute name="extend" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="item">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="key" type="xsd:string" minOccurs="0" />
				<xsd:element name="value" type="xsd:string" minOccurs="0" />
				<xsd:element name="label" type="xsd:string" minOccurs="0" />
			</xsd:sequence>
			<xsd:attributeGroup ref="itemAtt" />
		</xsd:complexType>
	</xsd:element>

	<xsd:attributeGroup name="itemAtt">
		<xsd:attribute name="key" type="xsd:string" />
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="label" type="xsd:string" />
	</xsd:attributeGroup>
	
</xsd:schema>

=== yun79831/toolTest/src/config/codemapping/fileupload.xml
<?xml version="1.0" encoding="GBK"?>
<constants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="codemapping.xsd">
	

	<!-- 上传配置 -->
	<constant id="global">
		<item key="endocing" value="GBK" label="编码"/>
		<item key="maxMemorySize" value="62M" label="最大内存使用量"/>
		<item key="maxSingleSize" value="60M" label="单个文件最大字节数"/>
		<item key="maxTotalSize" value="100M" label="总上传文件最大字节数"/>
		<item key="temporaryDir" value="${webhome}/WEB-INF/upload/temp" label="上传文件保存的临时目录"/>
		<item key="allowFiletype" value="jpg,jpeg,bmp,gif,png" label="允许的上传文件类型(类型必须是小写)"/>
	</constant>
	
	<constant id="xls">
		<item key="endocing" value="GBK" label="编码"/>
		<item key="maxMemorySize" value="10M" label="最大内存使用量"/>
		<item key="maxSingleSize" value="10M" label="单个文件最大字节数"/>
		<item key="maxTotalSize" value="10M" label="总上传文件最大字节数"/>
		<item key="temporaryDir" value="${webhome}/WEB-INF/upload/temp" label="上传文件保存的临时目录"/>
		<item key="allowFiletype" value="xls" label="允许的上传文件类型(类型必须是小写)"/>
	</constant>
	
	<constant id="doc">
		<item key="endocing" value="GBK" label="编码"/>
		<item key="maxMemorySize" value="10M" label="最大内存使用量"/>
		<item key="maxSingleSize" value="30M" label="单个文件最大字节数"/>
		<item key="maxTotalSize" value="30M" label="总上传文件最大字节数"/>
		<item key="temporaryDir" value="${webhome}/WEB-INF/upload/temp" label="上传文件保存的临时目录"/>
		<item key="allowFiletype" value="doc" label="允许的上传文件类型(类型必须是小写)"/>
	</constant>	
	
	<!-- 辅助配置 -->
	<constant id="imagetype">
		<item key="jpg" value="jpg" />
		<item key="jpeg" value="jpeg" />
		<item key="ico" value="ico" />
		<item key="bmp" value="bmp" />
		<item key="gif" value="gif" />
		<item key="png" value="png" />
	</constant>
	
	<constant id="word">
		<item key="autosave" value="5" label="单位是分钟"/>
		<item key="maxsize" value="1024*1024*30" label="单位是字节"/>
	</constant>
		
	<constant id="filenumber">
		<item key="base" value="2" />
	</constant>
	
	<constant id="printdownloadurl">
	<item key="ExpertList" value="e://ExpertList" label="专家名单"></item>
	</constant>
	
	<!-- <constant id="printdownloadurl">
	<item key="ExpertList" value="//opt//upload//ExpertList" label="专家名单"></item>
	</constant> -->
	<constant id="sync">
		<item key="logurl" value="e:/log.txt" label="同步专家分析日志"/>	
		<item key="failurl" value="e:/fail.txt" label="同步专家分析日志"/>	
	</constant>
</constants>

=== yun79831/toolTest/src/config/codemapping/system.xml
<?xml version="1.0" encoding="UTF-8"?>
<constants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="codemapping.xsd"> 
	
	<constant id="loginAccount">
		<item key="accounts" value="false" label="登录限制"/>
	</constant>
	<constant id="searchYear">
		<item key="beginYear" value="2008" label="起始年度"/>
	</constant>
	<constant id="pwd">
		<item key="expert" value="123456" label="专家重置密码"/>
		<item key="company" value="123456" label="单位重置密码"/>
		<item key="center" value="123456" label="中心重置密码"/>
	</constant>
</constants>
